import { NextResponse } from 'next/server';

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

export async function POST(req) {
  try {
    const { userData, analysis } = await req.json();

    // Try generating a real PDF using AstrologyAPI PDF endpoint
    // Docs: https://astrologyapi.com/docs/pdf-docs
    const API_USER_ID =  '643935';
    const API_KEY = '4b732fc899769224cf5b115c861e652b91f7d6a2';

    if (API_USER_ID && API_KEY) {
      try {
        // Parse birth fields
        const [y, m, d] = (userData.birthDate || '').split('-').map((v) => parseInt(v, 10));
        const [hh, mm] = (userData.birthTime || '00:00').split(':').map((v) => parseInt(v, 10));

        // Fallbacks
        const gender = (userData.gender || 'Male').toLowerCase();
        const place = userData.birthPlace || `${userData.birthCity || 'Delhi'}, ${userData.birthCountry || 'India'}`;
        const lat = 28.6139; // Delhi
        const lon = 77.2090; // Delhi
        const tzone = 5.5;

        const payload = {
          name: userData.name || 'User',
          gender,
          day: Number.isFinite(d) ? d : 1,
          month: Number.isFinite(m) ? m : 1,
          year: Number.isFinite(y) ? y : 2000,
          hour: Number.isFinite(hh) ? hh : 0,
          min: Number.isFinite(mm) ? mm : 0,
          lat,
          lon,
          language: 'en',
          tzone,
          place,
          chart_style: 'NORTH_INDIAN',
          footer_link: 'nakshatraone.com',
          logo_url: 'https://dummyimage.com/200x60/667eea/ffffff&text=NakshatraOne',
          company_name: 'NakshatraOne',
          company_info: 'Generated by NakshatraOne',
          domain_url: 'https://nakshatraone.com',
          company_email: '[email protected]',
          company_landline: '+91-22-1234 5678',
          company_mobile: userData.mobile || '+91-90000 00000'
        };

        const basic = Buffer.from(`${API_USER_ID}:${API_KEY}`).toString('base64');
        const apiRes = await fetch('https://pdf.astrologyapi.com/v1/basic_horoscope_pdf', {
          method: 'POST',
          headers: {
            'Authorization': `Basic ${basic}`,
            'Content-Type': 'application/json'
          },
          body: JSON.stringify(payload)
        });

        if (apiRes.ok) {
          const apiJson = await apiRes.json();
          if (apiJson && apiJson.pdf_url) {
            const pdfFetch = await fetch(apiJson.pdf_url, { cache: 'no-store' });
            if (!pdfFetch.ok) throw new Error('Failed to fetch PDF file');
            return new NextResponse(pdfFetch.body, {
              headers: {
                'Content-Type': 'application/pdf',
                'Content-Disposition': `attachment; filename="kundli-analysis-${(userData.name || 'report')}.pdf"`,
                'Cache-Control': 'no-store'
              }
            });
          }
        }
        // If API failed fall through to HTML export below
      } catch (e) {
        // ignore and fall back to HTML
      }
    }

    // Create a simple HTML template for the PDF
    const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <title>Kundli Analysis Report - ${userData.name}</title>
        <style>
          body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: #333;
          }
          .header {
            background: rgba(255, 255, 255, 0.95);
            padding: 20px;
            border-radius: 10px;
            margin-bottom: 20px;
            box-shadow: 0 4px 15px rgba(0,0,0,0.1);
          }
          .logo {
            font-size: 24px;
            font-weight: bold;
            background: linear-gradient(45deg, #ff6b6b, #feca57);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            margin-bottom: 10px;
          }
          .user-info {
            background: rgba(255, 255, 255, 0.95);
            padding: 20px;
            border-radius: 10px;
            margin-bottom: 20px;
            box-shadow: 0 4px 15px rgba(0,0,0,0.1);
          }
          .analysis-section {
            background: rgba(255, 255, 255, 0.95);
            padding: 20px;
            border-radius: 10px;
            margin-bottom: 20px;
            box-shadow: 0 4px 15px rgba(0,0,0,0.1);
          }
          .kundali-chart {
            background: rgba(255, 255, 255, 0.95);
            padding: 20px;
            border-radius: 10px;
            margin-bottom: 20px;
            box-shadow: 0 4px 15px rgba(0,0,0,0.1);
            text-align: center;
          }
          .chart-grid {
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            gap: 10px;
            max-width: 400px;
            margin: 0 auto;
          }
          .chart-cell {
            border: 2px solid #667eea;
            padding: 15px;
            border-radius: 8px;
            background: rgba(102, 126, 234, 0.1);
          }
          .chart-cell.center {
            background: rgba(255, 193, 7, 0.2);
            border-color: #ffc107;
          }
          .info-grid {
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            gap: 15px;
            margin-top: 15px;
          }
          .info-item {
            display: flex;
            align-items: center;
            gap: 10px;
          }
          .info-label {
            font-weight: bold;
            color: #667eea;
          }
          .analysis-grid {
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            gap: 20px;
          }
          .analysis-item {
            background: rgba(102, 126, 234, 0.1);
            padding: 15px;
            border-radius: 8px;
            border-left: 4px solid #667eea;
          }
          .analysis-title {
            font-weight: bold;
            margin-bottom: 10px;
            color: #667eea;
          }
          .recommendations {
            background: rgba(255, 255, 255, 0.95);
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 4px 15px rgba(0,0,0,0.1);
          }
          .recommendation-item {
            background: rgba(255, 193, 7, 0.1);
            padding: 10px;
            margin: 10px 0;
            border-radius: 5px;
            border-left: 3px solid #ffc107;
          }
          h1, h2, h3 {
            color: #667eea;
            margin-bottom: 15px;
          }
          .footer {
            text-align: center;
            margin-top: 30px;
            padding: 20px;
            background: rgba(255, 255, 255, 0.95);
            border-radius: 10px;
            box-shadow: 0 4px 15px rgba(0,0,0,0.1);
          }
        </style>
      </head>
      <body>
        <div class="header">
          <div class="logo">नक्षत्रOne</div>
          <h1>Kundli Analysis Report</h1>
          <p>Generated on: ${new Date().toLocaleDateString('en-IN')}</p>
        </div>

        <div class="user-info">
          <h2>Personal Information</h2>
          <div class="info-grid">
            <div class="info-item">
              <span class="info-label">Name:</span>
              <span>${userData.name}</span>
            </div>
            <div class="info-item">
              <span class="info-label">Gender:</span>
              <span>${userData.gender}</span>
            </div>
            <div class="info-item">
              <span class="info-label">Date of Birth:</span>
              <span>${userData.birthDate}</span>
            </div>
            <div class="info-item">
              <span class="info-label">Time of Birth:</span>
              <span>${userData.birthTime}</span>
            </div>
            <div class="info-item">
              <span class="info-label">Birth Place:</span>
              <span>${userData.birthPlace}</span>
            </div>
          </div>
        </div>

        <div class="kundali-chart">
          <h2>Kundali Chart</h2>
          <div class="chart-grid">
            <div class="chart-cell">
              <strong>House 1</strong><br>
              ${analysis.ascendant}
            </div>
            <div class="chart-cell">
              <strong>House 2</strong><br>
              Taurus
            </div>
            <div class="chart-cell">
              <strong>House 3</strong><br>
              Gemini
            </div>
            <div class="chart-cell">
              <strong>House 12</strong><br>
              Pisces
            </div>
            <div class="chart-cell center">
              <strong>Lagna</strong><br>
              ${analysis.ascendant}
            </div>
            <div class="chart-cell">
              <strong>House 4</strong><br>
              Cancer
            </div>
            <div class="chart-cell">
              <strong>House 11</strong><br>
              Aquarius
            </div>
            <div class="chart-cell">
              <strong>House 10</strong><br>
              Capricorn
            </div>
            <div class="chart-cell">
              <strong>House 5</strong><br>
              Leo
            </div>
            <div class="chart-cell">
              <strong>House 6</strong><br>
              Virgo
            </div>
            <div class="chart-cell">
              <strong>House 7</strong><br>
              Libra
            </div>
            <div class="chart-cell">
              <strong>House 8</strong><br>
              Scorpio
            </div>
          </div>
        </div>

        <div class="analysis-section">
          <h2>Astrological Analysis</h2>
          <div class="analysis-grid">
            <div class="analysis-item">
              <div class="analysis-title">Sun Sign</div>
              <div>${analysis.sunSign}</div>
            </div>
            <div class="analysis-item">
              <div class="analysis-title">Moon Sign</div>
              <div>${analysis.moonSign}</div>
            </div>
            <div class="analysis-item">
              <div class="analysis-title">Ascendant</div>
              <div>${analysis.ascendant}</div>
            </div>
            <div class="analysis-item">
              <div class="analysis-title">Nakshatra</div>
              <div>${analysis.nakshatra}</div>
            </div>
          </div>
        </div>

        <div class="analysis-section">
          <h2>Doshas & Strengths</h2>
          <div class="analysis-grid">
            <div class="analysis-item">
              <div class="analysis-title">Doshas</div>
              <div>${analysis.doshas.join(', ')}</div>
            </div>
            <div class="analysis-item">
              <div class="analysis-title">Strengths</div>
              <div>${analysis.strengths.join(', ')}</div>
            </div>
            <div class="analysis-item">
              <div class="analysis-title">Areas of Concern</div>
              <div>${analysis.weaknesses.join(', ')}</div>
            </div>
          </div>
        </div>

        <div class="recommendations">
          <h2>Recommendations</h2>
          ${analysis.recommendations.map((rec, index) => `
            <div class="recommendation-item">
              <strong>${index + 1}.</strong> ${rec}
            </div>
          `).join('')}
        </div>

        <div class="footer">
          <p><strong>नक्षत्रOne</strong> - Your Trusted Astrological Partner</p>
          <p>This report is generated based on Vedic astrology principles</p>
          <p>For detailed consultation, visit our website</p>
        </div>
      </body>
      </html>
    `;

    // Fallback: return HTML report if PDF API is not configured or failed
    return new NextResponse(htmlContent, {
      headers: {
        'Content-Type': 'text/html',
        'Content-Disposition': `attachment; filename="kundli-analysis-${userData.name}.html"`
      }
    });

  } catch (error) {
    console.error('Error generating PDF:', error);
    return NextResponse.json({ error: 'Failed to generate PDF' }, { status: 500 });
  }
} 